sudo: required
before_install:
    - sudo add-apt-repository -y ppa:fish-shell/release-2
    - sudo add-apt-repository ppa:git-core/ppa -y
    - sudo apt-get update
    - sudo apt-get -y install fish git
script:
    - git clone --depth 1 https://github.com/fisherman/fisherman && make -f fisherman/Makefile
    - fish -c "fisher update"
    - fish -c "fisher install fishtape ."
    - fish -c "fishtape test/*.fish"