sudo: required
before_install:
    - sudo add-apt-repository -y ppa:fish-shell/release-2
    - sudo add-apt-repository ppa:git-core/ppa -y
    - sudo apt-get update
    - sudo apt-get -y install fish git
script:
    - curl -sL get.fisherman.sh | fish
    - fish -c "fisher i fishtape .; fishtape test/*.fish"